import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";

import { Providers } from "../app/GlobalRedux/provider";

const mainFontFamily = Poppins({
  weight: ["400", "500", "600", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/@phosphor-icons/web"></script>
      </head>
      <body className={mainFontFamily.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
